// Resource types for the Fliq API. These mirror the request/response shapes of
// the Go core-api (see fliq-sh/core-api) and the dashboard client.

// ─── Jobs ───────────────────────────────────────────────────────────────────

export type JobStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

export type Backoff = "exponential" | "linear";

export interface Job {
  id: string;
  user_id: string;
  url: string;
  method: string;
  headers: Record<string, string> | null;
  body: string | null;
  status: JobStatus;
  scheduled_at: string;
  started_at: string | null;
  completed_at: string | null;
  attempts: number;
  max_retries: number;
  timeout_seconds: number;
  idempotency_key: string | null;
  webhook_url?: string | null;
  webhook_headers?: Record<string, string> | null;
  /** Set when this job was created by replaying a failed one — the source job id. */
  replay_of?: string | null;
  created_at: string;
  updated_at: string;
}

export interface JobAttempt {
  id: string;
  job_id: string;
  attempt_num: number;
  worker_id: string;
  started_at: string;
  completed_at: string | null;
  status_code: number | null;
  error: string | null;
}

export interface CreateJobInput {
  url: string;
  method: string;
  headers?: Record<string, string>;
  body?: string;
  scheduled_at: string;
  max_retries?: number;
  timeout_seconds?: number;
  /** Auto-generated by the SDK when omitted, so retries are safe by default. */
  idempotency_key?: string;
  backoff?: Backoff;
  webhook_url?: string;
  webhook_headers?: Record<string, string>;
}

export interface CreateJobResponse {
  id: string;
  created_at: string;
}

export interface ReplayJobResponse {
  id: string;
  status: JobStatus;
  replay_of?: string | null;
  scheduled_at: string;
  created_at: string;
}

export interface ListJobsParams {
  cursor?: string;
  limit?: number;
  status?: JobStatus;
}

export interface JobPage {
  jobs: Job[];
  next_cursor: string | null;
}

// ─── Schedules ──────────────────────────────────────────────────────────────

export interface Schedule {
  id: string;
  user_id: string;
  name: string;
  cron_expr: string;
  url: string;
  method: string;
  headers: Record<string, string> | null;
  body: string | null;
  paused: boolean;
  max_retries: number;
  timeout_seconds: number;
  next_run_at: string | null;
  last_run_at: string | null;
  webhook_url?: string | null;
  webhook_headers?: Record<string, string> | null;
  created_at: string;
  updated_at: string;
}

export interface CreateScheduleInput {
  name: string;
  cron_expr: string;
  url: string;
  method?: string;
  headers?: Record<string, string>;
  body?: string;
  max_retries?: number;
  timeout_seconds?: number;
  backoff?: Backoff;
  webhook_url?: string;
  webhook_headers?: Record<string, string>;
}

export interface ListSchedulesParams {
  cursor?: string;
  limit?: number;
}

export interface SchedulePage {
  schedules: Schedule[];
  next_cursor: string | null;
}

// ─── Buffers ────────────────────────────────────────────────────────────────

export type BufferItemStatus = "pending" | "running" | "completed" | "failed";

export interface Buffer {
  id: string;
  name: string;
  url: string;
  method: string;
  timeout_seconds: number;
  rate_limit: number;
  max_retries: number;
  backoff: Backoff;
  paused: boolean;
  webhook_url?: string | null;
  created_at: string;
  updated_at: string;
}

export interface BufferItem {
  id: string;
  buffer_id: string;
  status: BufferItemStatus;
  status_code: number | null;
  retry_count: number;
  max_retries: number;
  last_error: string | null;
  /** Set when this item was created by replaying a failed one — the source item id. */
  replay_of?: string | null;
  created_at: string;
  completed_at: string | null;
}

/** Per-buffer item status breakdown — server-aggregated (not page-limited). */
export interface BufferStats {
  pending: number;
  running: number;
  completed: number;
  failed: number;
  total: number;
  /** completed / (completed + failed), in [0,1]; 0 when none have finished. */
  success_rate: number;
}

export interface CreateBufferInput {
  name: string;
  url: string;
  method?: string;
  headers?: Record<string, string>;
  timeout_seconds?: number;
  rate_limit: number;
  max_retries?: number;
  backoff?: Backoff;
  webhook_url?: string;
  webhook_headers?: Record<string, string>;
}

export interface PushBufferItemInput {
  body?: string;
  headers?: Record<string, string>;
  /** Auto-generated by the SDK when omitted, so retries are safe by default. */
  idempotency_key?: string;
}

export interface ListBuffersParams {
  cursor?: string;
  limit?: number;
}

export interface ListBufferItemsParams {
  cursor?: string;
  limit?: number;
  status?: BufferItemStatus;
}

export interface BufferPage {
  buffers: Buffer[];
  next_cursor: string | null;
}

export interface BufferItemPage {
  items: BufferItem[];
  next_cursor: string | null;
}

// ─── Alerts ─────────────────────────────────────────────────────────────────

export type AlertChannelType = "webhook" | "slack";

export interface AlertChannel {
  id: string;
  type: AlertChannelType;
  target: string;
  name: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateAlertChannelInput {
  type: AlertChannelType;
  target: string;
  name?: string;
}

export interface AlertChannelList {
  channels: AlertChannel[];
}

// ─── Stats ──────────────────────────────────────────────────────────────────

export interface JobStats {
  total_executions: number;
  succeeded: number;
  failed: number;
  /** succeeded / total_executions, in [0,1]. */
  success_rate: number;
  avg_duration_ms: number;
  p95_duration_ms: number;
  since_days: number;
}

export interface UsageBucket {
  date: string; // UTC day, "YYYY-MM-DD"
  job_executions: number;
  buffer_executions: number;
}

export interface UsageSummary {
  buckets: UsageBucket[];
  total_job_executions: number;
  total_buffer_executions: number;
  balance: number;
  plan: Plan;
  since_days: number;
}

// ─── Billing ────────────────────────────────────────────────────────────────

export type Plan = "free" | "paid";

export interface BillingBalance {
  balance: number;
  plan: Plan;
  daily_limit: number;
  credits_per_dollar: number;
}

export type CreditTxType = "job_execution" | "daily_grant" | "stripe_topup";

export interface CreditTransaction {
  id: string;
  amount: number;
  type: CreditTxType;
  job_id: string | null;
  stripe_payment_intent_id: string | null;
  description: string | null;
  created_at: string;
}

export interface ListTransactionsParams {
  cursor?: string;
  limit?: number;
}

export interface CreditTransactionPage {
  transactions: CreditTransaction[];
  next_cursor: string | null;
}

export interface CheckoutResponse {
  url: string;
}

// ─── Tokens ─────────────────────────────────────────────────────────────────

export interface APIToken {
  id: string;
  name: string;
  prefix: string;
  last_used_at: string | null;
  created_at: string;
}

export interface CreateTokenResponse {
  id: string;
  name: string;
  prefix: string;
  /** Raw token — shown once, never stored. */
  token: string;
  created_at: string;
}
